trigger:
- master
- main

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  feedName: 'Lab4Feed'
  feedUrl: 'https://pkgs.dev.azure.com/Comp367001-JNS/_packaging/Lab4Feed/nuget/v3/index.json'

steps:
# Ensure NuGet is available
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'
  inputs:
    versionSpec: '5.x'
    checkLatest: true

# Authenticate NuGet Feed
- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet Feed'
  inputs:
    nuGetServiceConnections: 'Lab4Feed'

# Restore Dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore Dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '$(feedName)'

# Pack NuGet Package
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringExtensionsLibrary.csproj'
    configuration: '$(buildConfiguration)'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'

# Push NuGet Package using DotNet CLI
- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Package'
  inputs:
    command: 'nuget'
    nuGetCommand: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(feedName)'

# Fallback Push Method
- script: |
    dotnet nuget push $(Build.ArtifactStagingDirectory)/**/*.nupkg \
      --source "$(feedUrl)" \
      --api-key AzureDevOps
  displayName: 'Fallback NuGet Push'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

# Diagnostic Logging
- powershell: |
    Write-Host "Packages in Artifact Directory:"
    Get-ChildItem "$(Build.ArtifactStagingDirectory)" -Filter *.nupkg | ForEach-Object {
      Write-Host $_.FullName
    }
    
    Write-Host "`n.NET SDK Versions:"
    dotnet --list-sdks
    
    Write-Host "`nNuGet Sources:"
    dotnet nuget list source
  displayName: 'Diagnostics and Logging'