trigger:
- master
- main

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  feedName: 'Lab4Feed'

steps:
# Diagnostic Logging for Permissions
- powershell: |
    Write-Host "Build Service Principal ID: $(System.AccessToken)"
    Write-Host "Current User: $env:USERNAME"
  displayName: 'Diagnose User Context'

- task: DotNetCoreCLI@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet Feed'
  inputs:
    nuGetServiceConnections: 'Lab4Feed'

- task: DotNetCoreCLI@2
  displayName: 'Restore Dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '$(feedName)'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringExtensionsLibrary.csproj'
    configuration: '$(buildConfiguration)'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'

# Alternative Push Method
- task: DotNetCoreCLI@2
  displayName: 'Push NuGet Package'
  inputs:
    command: 'nuget'
    nuGetCommand: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(feedName)'

# Diagnostic Logging
- powershell: |
    Write-Host "Packages in Artifact Directory:"
    Get-ChildItem "$(Build.ArtifactStagingDirectory)" -Filter *.nupkg | ForEach-Object {
      Write-Host $_.FullName
    }
  displayName: 'List NuGet Packages'