trigger:
- master

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  feedName: 'Lab4Feed'
  # Explicitly define version
  majorVersion: '1'
  minorVersion: '0'
  patchVersion: '$(Build.BuildId)'  # Use Build ID for unique versioning

steps:
- task: DotNetCoreCLI@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet Feed'
  inputs:
    nuGetServiceConnections: 'Lab4Feed'

- task: DotNetCoreCLI@2
  displayName: 'Restore Dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '$(feedName)'

- task: DotNetCoreCLI@2
  displayName: 'Build Project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet Package'
  inputs:
    command: 'pack'
    packagesToPack: '**/StringExtensionsLibrary.csproj'
    # Explicit versioning configuration
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'CUSTOM_PACKAGE_VERSION'

# Set custom version before packing
- bash: |
    echo "##vso[task.setvariable variable=CUSTOM_PACKAGE_VERSION]$(majorVersion).$(minorVersion).$(patchVersion)"
  displayName: 'Set Package Version'

- task: NuGetCommand@2
  displayName: 'Push NuGet Package'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(feedName)'
    allowPackageConflicts: true

# Diagnostic Logging
- bash: |
    echo "Build Number: $(Build.BuildNumber)"
    echo "Build ID: $(Build.BuildId)"
    echo "Package Version: $(CUSTOM_PACKAGE_VERSION)"
  displayName: 'Version Diagnostics'